version: "3.8"

services:
  andrade:
    image: ghcr.io/dkcatotin/andrade:1.0.5
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # --- REDIRECCIÓN HTTP → HTTPS ---
        - "traefik.http.routers.andrade.entrypoints=http"
        - "traefik.http.routers.andrade.rule=Host(`andrade.byronrm.com`)"
        - "traefik.http.middlewares.andrade-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.andrade.middlewares=andrade-https-redirect"

        # --- ROUTER HTTPS ---
        - "traefik.http.routers.andrade-secure.entrypoints=https"
        - "traefik.http.routers.andrade-secure.rule=Host(`andrade.byronrm.com`)"
        - "traefik.http.routers.andrade-secure.tls=true"
        - "traefik.http.routers.andrade-secure.tls.certresolver=http"
        - "traefik.http.routers.andrade-secure.service=andrade"

        # ⭐ Puerto interno real de la app Flask
        - "traefik.http.services.andrade.loadbalancer.server.port=8080"

        # Red de Traefik
        - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
